name: Latest blog post workflow

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://tanishmhatre.substack.com/feed"
          max_post_count: 5
          committer_username: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
